resolver: lts-12.26

packages:
- '.'

extra-deps: # []
- network-socket-options-0.2.0.1

flags: {}

extra-package-dbs: []

build:
  library-profiling: false
  executable-profiling: false

# allow-newer: true
# rebuild-ghc-options: true
